services:
    _defaults:
        autowire: true,
        autoconfigure: true,
        public: true

    Markocupic\RszMemberListingBundle\:
        resource: ../src/
        exclude: ../src/{DependencyInjection,ContaoManager,Model}
